# _quarto.yml
project:
  type: website
  output-dir: _site

website:
  title: "ISSS608-VAA"
  navbar:
    background: dark
    foreground: light
    search: true
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "1. A Layered Grammar of Graphics: ggplot2 methods"
            href: Hands_on_Ex01.qmd
          - text: "2. Beyond ggplot2 Fundamentals"
            href: Hands_on_Ex02.qmd
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show code block"

editor: visual