# _quarto.yml
project:
  type: website
  output-dir: _site

website:
  title: |
    <img src="Hands-on Exercises/Hands-on W1/Mario 6.png" height="40" style="vertical-align:middle; margin-right:10px;">
    MINH'S VISUAL ANALYTICS WEBSITE
  favicon: Hands-on Exercises/Hands-on W1/Mario.png 
  navbar:
    background: dark
    foreground: light
    search: true
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "1. A Layered Grammar of Graphics: ggplot2 methods"
            href: Hands_on_Ex01.qmd
          - text: "2. Beyond ggplot2 Fundamentals"
            href: Hands_on_Ex02.qmd
          - text: "3a. Programming Interactive Data Visualisation with R"
            href: Hands_on_Ex03.qmd
          - text: "3b. Programming Animated Statistical Graphics with R"
            href: Hands_on_Ex03_2.qmd
          - text: "4a. Visualing Distribution"
            href: Hands_on_Ex04_1.qmd
          - text: "4b. Visual Statistical Analysis"
            href: Hands_on_Ex04_2.qmd
          - text: "4c. Visualising Uncertainty"
            href: Hands_on_Ex04_3.qmd
          - text: "4d. Funnel Plots for Fair Comparisons"
            href: Hands_on_Ex04_4.qmd
          - text: "5a. Creating Ternary Plot with R"
            href: Hands_on_Ex05_1.qmd
          - text: "5b. Visual Correlation Analysis"
            href: Hands_on_Ex05_2.qmd
          - text: "5c. Heatmap for Visualising and Analysing Multivariate Data"
            href: Hands_on_Ex05_3.qmd
          - text: "5d. Visual Multivariate Analysis with Parallel Coordinates Plot"
            href: Hands_on_Ex05_4.qmd
          - text: "5e. Treemap Visualisation with R"
            href: Hands_on_Ex05_5.qmd
        - text: "Take-home Exercise"
        menu:
            
            
            
          
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Show code block"
    
execute:
  warning: false
  message: false
  echo: true
  fig-width: 15
  fig-height: 9
  fig-align: center
  out-width: "100%"

editor: visual